version: "3"
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    ports:
      - 10022:22/tcp
      - 13000:3000/tcp
    restart: always
    volumes:
      - /home/jacob/Docker/Gitea:/data
networks:
  default:
    external:
      name: docker-network
