version: "3"
services:
  cyberchef:
    container_name: cyberchef
    image: suika/cyberchef
    ports:
      - 10085:80/tcp
    restart: always
networks:
  default:
    external:
      name: docker-network
