version: "3"
services:
  draw:
    container_name: draw
    image: jgraph/drawio:latest
    ports:
      - 19080:8080/tcp
      - 19443:8443/tcp
    restart: always
networks:
  default:
    external:
      name: docker-network
