version: "3"
services:
  watchtower:
    container_name: watchtower
    expose:
      - 8080/tcp
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 6 * * *" --cleanup
networks:
  default:
    external:
      name: docker-network
