version: "3"
services:
  ebooks:
    container_name: ebooks
    image: httpd
    ports:
      - 16080:80/tcp
    restart: always
    volumes:
      - /mnt/Ebooks:/usr/local/apache2/htdocs
networks:
  default:
    external:
      name: docker-network
