version: "3"
services:
  nullboard:
    build: .
    image: jcurtis4207/nullboard
    restart: always
    ports: 
     - 20080:80
    ### chown www-data:www-data <path-to-volume>
    volumes:
     - /home/jacob/Docker/Nullboard:/var/www/html/PHP/DB
    container_name: nullboard
networks:
  default:
    external:
      name: docker-network

