version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - 8000:8000/tcp
      - 9000:9000/tcp
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jacob/Docker/Portainer:/data
networks:
  default:
    external:
      name: docker-network
