version: "3"
services:
  syncthing:
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    image: linuxserver/syncthing:latest
    ports:
      - 21027:21027/udp
      - 22000:22000/tcp
      - 18384:8384/tcp
    restart: always
    volumes:
      - /home/jacob/Docker/Syncthing:/config
networks:
  default:
    external:
      name: docker-network
